stages:
  - analysis
  - build
  - test

before_script:
  - hostname
  - whoami
# - pwd
  - git submodule sync --recursive
  - git submodule update --init --recursive

analysis-cppcheck:
  stage: analysis
  artifacts:
     name: analysis-cppcheck-logs
     when: always
     paths:
       - cppcheck/
  tags:
    - cppcheck
  script:
    - ./ci/analysis-cppcheck.sh

build-linux-gcc:
  stage: build
  tags:
   - linux
  cache:
    paths:
      - ./tests/build_gcc_nointr/
      - ./tests/build_gcc_sse2/
      - ./tests/build_gcc_sse3/
      - ./tests/build_gcc_ssse3/
      - ./tests/build_gcc_sse4_1/
      - ./tests/build_gcc_sse4_2/
      - ./tests/build_gcc_avx/
      - ./tests/build_gcc_avx2/
      - ./tests/build_gcc_avx2_fma/
      - ./tests/build_gcc_avx512f/
  script:
    - ./ci/build-linux-gcc.sh

build-linux-clang:
  stage: build
  tags:
   - linux
  cache:
    paths:
      - ./tests/build_clang_nointr/
      - ./tests/build_clang_sse2/
      - ./tests/build_clang_sse3/
      - ./tests/build_clang_ssse3/
      - ./tests/build_clang_sse4_1/
      - ./tests/build_clang_sse4_2/
      - ./tests/build_clang_avx/
      - ./tests/build_clang_avx2/
      - ./tests/build_clang_avx2_fma/
  script:
    - ./ci/build-linux-clang.sh

build-linux-icpc:
  stage: build
  tags:
   - linux
  cache:
    paths:
      - ./tests/build_icpc_nointr/
      - ./tests/build_icpc_sse2/
      - ./tests/build_icpc_sse3/
      - ./tests/build_icpc_ssse3/
      - ./tests/build_icpc_sse4_1/
      - ./tests/build_icpc_sse4_2/
      - ./tests/build_icpc_avx/
      - ./tests/build_icpc_avx2/
      - ./tests/build_icpc_avx2_fma/
      - ./tests/build_icpc_avx512f/
  script:
    - ./ci/build-linux-icpc.sh

test-linux-unit-nointr:
  stage: test
  tags:
    - linux
  cache:
    paths:
      - ./tests/build_gcc_nointr/
      - ./tests/build_clang_nointr/
      - ./tests/build_icpc_nointr/
  script:
    - ./ci/test-linux-unit.sh build_gcc_nointr build_clang_nointr build_icpc_nointr

test-linux-unit-sse2:
  stage: test
  tags:
    - linux
  cache:
    paths:
      - ./tests/build_gcc_sse2/
      - ./tests/build_clang_sse2/
      - ./tests/build_icpc_sse2/
  script:
    - ./ci/test-linux-unit.sh build_gcc_sse2 build_clang_sse2 build_icpc_sse2

test-linux-unit-sse3:
  stage: test
  tags:
    - linux
  cache:
    paths:
      - ./tests/build_gcc_sse3/
      - ./tests/build_clang_sse3/
      - ./tests/build_icpc_sse3/
  script:
    - ./ci/test-linux-unit.sh build_gcc_sse3 build_clang_sse3 build_icpc_sse3

test-linux-unit-ssse3:
  stage: test
  tags:
    - linux
  cache:
    paths:
      - ./tests/build_gcc_ssse3/
      - ./tests/build_clang_ssse3/
      - ./tests/build_icpc_ssse3/
  script:
    - ./ci/test-linux-unit.sh build_gcc_ssse3 build_clang_ssse3 build_icpc_ssse3

test-linux-unit-sse4_1:
  stage: test
  tags:
    - linux
  cache:
    paths:
      - ./tests/build_gcc_sse4_1/
      - ./tests/build_clang_sse4_1/
      - ./tests/build_icpc_sse4_1/
  script:
    - ./ci/test-linux-unit.sh build_gcc_sse4_1 build_clang_sse4_1 build_icpc_sse4_1

test-linux-unit-sse4_2:
  stage: test
  tags:
    - linux
  cache:
    paths:
      - ./tests/build_gcc_sse4_2/
      - ./tests/build_clang_sse4_2/
      - ./tests/build_icpc_sse4_2/
  script:
    - ./ci/test-linux-unit.sh build_gcc_sse4_2 build_clang_sse4_2 build_icpc_sse4_2

# test-linux-unit-avx:
#   stage: test
#   tags:
#     - linux
#   cache:
#     paths:
#       - ./tests/build_gcc_avx/
#       - ./tests/build_clang_avx/
#       - ./tests/build_icpc_avx/
#   script:
#     - ./ci/test-linux-unit.sh build_gcc_avx build_clang_avx build_icpc_avx

# test-linux-unit-avx2:
#   stage: test
#   tags:
#     - linux
#   cache:
#     paths:
#       - ./tests/build_gcc_avx2/
#       - ./tests/build_clang_avx2/
#       - ./tests/build_icpc_avx2/
#   script:
#     - ./ci/test-linux-unit.sh build_gcc_avx2 build_clang_avx2 build_icpc_avx2

# test-linux-unit-avx2_fma:
#   stage: test
#   tags:
#     - linux
#   cache:
#     paths:
#       - ./tests/build_gcc_avx2_fma/
#       - ./tests/build_clang_avx2_fma/
#       - ./tests/build_icpc_avx2_fma/
#   script:
#     - ./ci/test-linux-unit.sh build_gcc_avx2_fma build_clang_avx2_fma build_icpc_avx2_fma